<a href="https://colab.research.google.com/github/Songurdevoloper/Trace-operator-and-frobenius-norm-equation/blob/main/Trace_operator_and_frobenius_norm_equation_ipynT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### The Trace Operator

Denoted as **Tr(A)**. Simply the sum of the diagonal elements of a matrix:

In [2]:
import numpy as np
import torch
import tensorflow as tf

In [4]:
A = np.array([[35, 8], [26, 11]])
A

array([[35,  8],
       [26, 11]])

In [6]:
np.trace(A) # 35 + 11 (sum of the diagonal elements)

46

The trace operator has a number of useful properties that come in handy while rearranging linear algebra equations, e.g.:

- Tr(A) = Tr(A<sup>T</sup>)
- Assuming the matrix shapes line up: Tr(ABC) = Tr(CBA) = Tr(BCA)

In particular, the trace operator can provide a convenient way to calculate a matrix's Frobenius norm: 
**‖A‖<sub>F</sub> = √Tr(AA<sup>T</sup>)**

**Exercises**

With the matrix `A_p` provided below:

1st
- Use the PyTorch trace method to calculate the trace of `A_pt`
- Use the PyTorch Frobenius norm method and the trace method to demonstrate that 

2st
- Use the TensorFlow trace method to calculate the trace of `A_tf`
- Use the TensorFlow Frobenius norm method and the trace method to demonstrate that 

<h3>‖A‖<sub>F</sub> = √Tr(AA<sup>T</sup>)</h3>

**PyTorch**

In [13]:
A_pt = torch.tensor([[12, 24], [-3, 7], [9, -2.]])
A_pt

tensor([[12., 24.],
        [-3.,  7.],
        [ 9., -2.]])

Use Frobenius norm to calculate our matrix `A_pt`

In [15]:
A_pt_frob_norm = torch.frobenius_norm(A_pt)
A_pt_frob_norm

tensor(29.3769)

Use trace method the calculate our matrix `A_pt`

In [17]:
A_pt_trace = torch.sqrt(torch.trace(torch.matmul(A_pt, A_pt.T)))
A_pt_trace

tensor(29.3769)

Now we'll check Frobenius norm method and the trace method to show if whether equation equals!

In [18]:
A_pt_frob_norm == A_pt_trace

tensor(True)

**TensorFlow**

In [20]:
A_tf = tf.Variable([[12, 2], [-14, 5], [2, -9.]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[ 12.,   2.],
       [-14.,   5.],
       [  2.,  -9.]], dtype=float32)>

Use Frobenius norm to calculate our matrix `A_tf`

In [22]:
A_tf_frob_norm = tf.norm(A_tf)
A_tf_frob_norm

<tf.Tensor: shape=(), dtype=float32, numpy=21.307276>

Use trace method the calculate our matrix `A_tf`

In [24]:
A_tf_trace = tf.sqrt(tf.linalg.trace(tf.matmul(A_tf, tf.transpose(A_tf))))
A_tf_trace

<tf.Tensor: shape=(), dtype=float32, numpy=21.307276>

Now we'll check Frobenius norm method and the trace method to show if whether equation equals!

In [25]:
A_tf_frob_norm == A_tf_trace

<tf.Tensor: shape=(), dtype=bool, numpy=True>